// Lab6_Interrupts.c
// Eric Santana
// Group 2

#include "tm4c123gh6pm.h"
#include <stdint.h> // C99 data types


// TODO: define bit addresses for the three LEDs connected to PORTF
#define LED        (*((volatile uint32_t *)0x40025038))   
#define SW2        (*((volatile uint32_t *)0x40025004))   
	
// TODO: Define the three LED bit positions
#define RED  			0x02
#define BLUE 			0x04
#define GREEN			0x08
#define SW2_MASK  0x01

// TODO: define constants used in this project.
#define HALF_S 							8000000U          // Assume the system clock is 16MHz.
																				// define number of clock cycles to generate 0.5s time interval.
                                        // A U follows a constant indicate this is an unsigned number

#define NVIC_EN0_PORTF		  0x40000000  // bit position for PORTF interrupt in NVIC_EN0_R register.

#define SYSCTL_RCGC2_R    	(*((volatile unsigned long *)0x400FE108))
	

// PORT F Register Setup: Output
#define SYSCTL_RCGC2_GPIOF   	0x00000020     	// port F Clock Gating Control
#define PORTF_DIR_CODE 				0x0E						// Set Bits F3-F1 as output
#define PORTF_AFSEL_CODE 			0x00 						//Disable AFSEL 
#define PORTF_DEN_CODE 				0x0F 						// Enable Bits F3-F0
#define PORTF_AMSEL_CODE 			0x00 						// Disable AMSEL
#define PORTF_PCTL_CODE 			0x0000FFFF 			// Disable PCTL
#define PORTF_LOCK_CODE				0x4C4F434B			// Unlock Port F
#define PORTF_CR_CODE					0x1F						// Allow Changes to port F: F4-F0



// Function Prototypes (external functions from startup.s)
extern void DisableInterrupts(void); // Disable interrupts
extern void EnableInterrupts(void);  // Enable interrupts
extern void WaitForInterrupt(void);  // Go to low power mode while waiting for the next interrupt

// Function Prototypes
// Initialize rising edge triggered interrupt for PF0 (SW2) and three LEDs on Port F
void Switch_LED_Init(void);  

// Initialize SysTick timer with interrupt enabled.
// Parameter "period" specifies number of counts for the time 
// period generated by systick timer.
void SysTick_Init(uint32_t period);      

// global variable visible in Watch and Memory window of debugger:
// used for the purpose of practicing debug: use watch window and memory window 
// to keep track of varaible values and memory contents.
// This variable helps keeping track of number of button presses: 
// it increments once per button release.
volatile uint32_t RisingEdges = 0;

// keep track of the current active LED
volatile uint8_t curr_led = RED;

int main(void){
	DisableInterrupts();
  Switch_LED_Init();
	SysTick_Init(HALF_S);
	EnableInterrupts();
	
	// initialize current active LED to be red
	LED = RED;
	curr_led = RED;
	
  while(1){
		WaitForInterrupt();
  }
}


// TODO: Initialize rising edge triggered interrupt 
// for PF0 (SW2) and three LEDs on Port F
void Switch_LED_Init(void) {
	
	SYSCTL_RCGC2_R |= SYSCTL_RCGC2_GPIOF;
	
	// wait for clock to be active
	while ((SYSCTL_RCGC2_R & SYSCTL_RCGC2_GPIOF) != SYSCTL_RCGC2_GPIOF){}
		
	//Setup GPIO Port F
	GPIO_PORTF_LOCK_R |= PORTF_LOCK_CODE; // unlock port F
	GPIO_PORTF_CR_R		|= PORTF_CR_CODE;		// allow changes to F pins
	GPIO_PORTF_AMSEL_R &=~(PORTF_AMSEL_CODE); // Disable analog function 
	GPIO_PORTF_PCTL_R &=~(PORTF_PCTL_CODE);  // Enable regular GPIO
  GPIO_PORTF_DIR_R  |= PORTF_DIR_CODE;  // Outputs on F3-F1
  GPIO_PORTF_AFSEL_R  &=~(PORTF_AFSEL_CODE);  // Regular function 
  GPIO_PORTF_DEN_R  |= (PORTF_DEN_CODE);    // Enable digital on F3-F0
	
	// Setup GPIO PORT F Interupt
		
  GPIO_PORTF_IS_R &= ~(0x0F); // Enable Edge Sesnsitive
	GPIO_PORTF_IBE_R &= ~(0x0F);// Disable Both Edge Sensitive
	GPIO_PORTF_IEV_R |= 0x0F; // F3-F0 Is rising edge sensitive
	GPIO_PORTF_ICR_R |= 0x0F; // Clear Flag F3-F0
	GPIO_PORTF_IM_R |= 0x01; // Arm Interupt for F0
	NVIC_PRI7_R = (NVIC_PRI7_R&0xFF1FFFFF) | 0x00A00000; // Give priority 5
	NVIC_EN0_R |= 0x40000000; // Enable interrrupt 30 in NVIC
	
	
}

// TODO: Initialize SysTick timer with interrupt enabled.
// Parameter "period" specifies number of counts for the time 
void SysTick_Init(uint32_t period) {
}

// TODO: ISR that Handles GPIO Port F interrupts. 
// When Port F interrupt triggers, do what's necessary then increment global variable RisingEdges
void GPIOPortF_Handler(void) {
	// simple solution to take care of button debounce: 20ms to 30ms delay
  for (uint32_t i=0;i<160000;i++) {}	
}

// TODO: ISR that Handles SysTick generated interrupts. 
// When timer interrupt triggers, do what's necessary then toggle the current LED
void SysTick_Handler(void) {
}
